### ISSUE TITLE
French strings

### ISSUE THREAD

**Issue by malvese** [roylodder/kirby-today#1]
If you ever want to add languages, either in a `lang` folder or in the docs so we can copy and paste, here are the French strings:

```
l::set('monday', 'lundi');
l::set('tuesday', 'mardi');
l::set('wednesday', 'mercredi');
l::set('thursday', 'jeudi');
l::set('friday', 'vendredi');
l::set('saterday', 'samedi');
l::set('sunday', 'dimanche');
```
Days are not capitalized in French (unless its the first word in a sentence of course).

**Comment by roylodder** [comment]
Thanks! Will add them to the docs.

**Comment by roylodder** [comment]
@malvese i created a language folder in the project and added your translation. Thanks again!

**Comment by malvese** [comment]
:+1:
